"""Datalevin Python bindings over the JVM interop bridge."""

from ._interop import (
    abort_transact,
    analyze,
    api_info,
    cardinality,
    connect,
    datalog_kv,
    datom,
    datom_a,
    datom_added,
    datom_e,
    datom_is,
    datom_tx,
    datom_v,
    embedding_attr,
    embedding_options,
    exec_json,
    explicit_transaction_timeout,
    fill_db,
    fulltext_attr,
    idoc_attr,
    idoc_domain,
    idoc_options,
    init_db,
    keyword,
    max_eid,
    new_client,
    new_search_engine,
    new_vector_index,
    open_kv,
    read_edn,
    re_index,
    schema_attr,
    search_index_writer,
    search_domain,
    search_options,
    set_explicit_transaction_timeout,
    symbol,
    transact,
    transact_async,
    tx_add,
    tx_data_to_simulated_report,
    tx_entity,
    tx_retract,
    tx_retract_entity,
    vector_attr,
    vector_options,
    with_transaction,
    write_edn,
)
from ._jvm import jvm_started, start_jvm
from ._raw import interop
from .client import Client
from .connection import Connection
from .database import Database
from .entity import Entity
from .errors import (
    DatalevinConfigurationError,
    DatalevinError,
    DatalevinJavaError,
    DatalevinJvmError,
)
from .kv import KV, KVTransaction, RawBuffer, RawKV
from .llm import LlamaEmbedder, LlamaGenerator, new_llama_embedder, new_llama_generator
from .search import (
    SearchEngine,
    SearchIndexWriter,
    create_analyzer,
    create_max_length_token_filter,
    create_min_length_token_filter,
    create_ngram_token_filter,
    create_regexp_tokenizer,
    create_stemming_token_filter,
    create_stop_words_token_filter,
    en_stop_words_token_filter,
    lower_case_token_filter,
    prefix_token_filter,
    unaccent_token_filter,
)
from .udf import UdfRegistry, create_udf_registry, udf_descriptor
from .vector import VectorIndex

__all__ = [
    "Client",
    "Connection",
    "Database",
    "DatalevinConfigurationError",
    "Entity",
    "DatalevinError",
    "DatalevinJavaError",
    "DatalevinJvmError",
    "KV",
    "KVTransaction",
    "LlamaEmbedder",
    "LlamaGenerator",
    "SearchEngine",
    "SearchIndexWriter",
    "RawBuffer",
    "RawKV",
    "UdfRegistry",
    "VectorIndex",
    "abort_transact",
    "analyze",
    "api_info",
    "cardinality",
    "connect",
    "create_analyzer",
    "create_max_length_token_filter",
    "create_min_length_token_filter",
    "create_ngram_token_filter",
    "create_regexp_tokenizer",
    "create_stemming_token_filter",
    "create_stop_words_token_filter",
    "create_udf_registry",
    "datom",
    "datom_a",
    "datom_added",
    "datom_e",
    "datom_is",
    "datom_tx",
    "datom_v",
    "datalog_kv",
    "embedding_attr",
    "embedding_options",
    "en_stop_words_token_filter",
    "exec_json",
    "explicit_transaction_timeout",
    "fill_db",
    "fulltext_attr",
    "idoc_attr",
    "idoc_domain",
    "idoc_options",
    "init_db",
    "interop",
    "jvm_started",
    "keyword",
    "lower_case_token_filter",
    "max_eid",
    "new_client",
    "new_llama_embedder",
    "new_llama_generator",
    "new_search_engine",
    "new_vector_index",
    "open_kv",
    "prefix_token_filter",
    "read_edn",
    "re_index",
    "schema_attr",
    "search_index_writer",
    "search_domain",
    "search_options",
    "set_explicit_transaction_timeout",
    "start_jvm",
    "symbol",
    "transact",
    "transact_async",
    "tx_add",
    "tx_data_to_simulated_report",
    "tx_entity",
    "tx_retract",
    "tx_retract_entity",
    "udf_descriptor",
    "unaccent_token_filter",
    "vector_attr",
    "vector_options",
    "with_transaction",
    "write_edn",
]

__version__ = "0.10.18"
