(ns datalevin.test.codec.nippy-support
  "Reference values from the resolved Nippy library and existing Datalevin freezers."
  (:require
   [clojure.string :as str]
   [taoensso.nippy :as nippy]
   [datalevin.datom :as datom]
   [datalevin.sparselist :as sparse]
   [datalevin.spill :as spill])
  (:import
   [datalevin.utl GrowingIntArray]
   [org.roaringbitmap RoaringBitmap]
   [java.util HexFormat]))

(defn bytes->hex [^bytes bytes] (.formatHex (HexFormat/of) bytes))
(defn hex->bytes ^bytes [^String hex] (.parseHex (HexFormat/of) hex))

(defn bitmap [values]
  (let [bitmap (RoaringBitmap.)]
    (doseq [n values] (.add bitmap (unchecked-int n)))
    bitmap))

(defn growing [values]
  (doto (GrowingIntArray.) (.addAll (int-array values))))

(defn native-fixtures
  "Independent JVM expectations for the Rust-authored fixture values."
  []
  {"nil" nil, "true" true, "false" false,
   "char" \ಬ, "surrogate" (char 0xd800),
   "byte" (byte -128), "short" (short -32768), "integer" Integer/MIN_VALUE,
   "long-min" Long/MIN_VALUE, "long-max" Long/MAX_VALUE,
   "long-boundaries" [0 1 -1 127 128 255 256 -255 -256 65535 65536 -65536 4294967295 4294967296],
   "float" (float 3.5), "double" -3.5,
   "bigint" 128N, "biginteger" (biginteger -129), "bigdec" 123.45M, "ratio" 22/7,
   "text" "ಬಾ ಇಲ್ಲಿ ಸಂಭವಿಸ", "keyword" :some/name, "symbol" 'some/name,
   "bytes" (byte-array [0 -128 -1]),
   "map" (array-map :a 1 :b 2), "set" #{1 2}, "sorted-set" (sorted-set 1 2),
   "sorted-map" (sorted-map :a 1), "list" (list 1 2), "seq" (map identity [1 2]),
   "queue" (into clojure.lang.PersistentQueue/EMPTY [1 2]),
   "entry" (clojure.lang.MapEntry/create "key" "val"),
   "meta" (with-meta [1] {:m true}), "regex" #"(?i)hello",
   "uri" (java.net.URI. "https://clojure.org"), "uuid" (java.util.UUID. 0 0),
   "date" (java.util.Date. 1577884455500), "sql-date" (java.sql.Date. 1577884455500),
   "instant" (java.time.Instant/ofEpochSecond 100 12),
   "duration" (java.time.Duration/ofSeconds -100 12), "period" (java.time.Period/of 1 -2 3),
   "int-array" (int-array [Integer/MIN_VALUE 0 Integer/MAX_VALUE]),
   "boolean-array" (boolean-array [true false true]),
   "short-array" (short-array [Short/MIN_VALUE 0 Short/MAX_VALUE]),
   "char-array" (char-array (map char [0 0xd800 0xffff])),
   "long-array" (long-array [Long/MIN_VALUE 0 Long/MAX_VALUE]),
   "float-array" (float-array [Float/NaN -0.0 Float/POSITIVE_INFINITY]),
   "double-array" (double-array [Double/NaN -0.0 Double/NEGATIVE_INFINITY]),
   "string-array" (into-array String [nil "hello"]), "object-array" (object-array [1 :a]),
   "record" (taoensso.nippy.StressRecord. "data"),
   "deftype" (taoensso.nippy.StressType. "normal field" "private field"),
   "datom" (datom/datom 42 :name "Ada" -536870913),
   "bitmap" (bitmap [0 1 65536 4294967295]),
   "growing-small" (growing [1 -1 7]),
   "growing-packed" (growing (map #(if (zero? (mod % 31)) (- %) %) (range 257))),
   "sparse" (sparse/->SparseIntArrayList (bitmap [0 65536 4294967295]) (growing [1 -1 7])),
   "spill-vector" (spill/new-spillable-vector [1 :a]),
   "spill-map" (spill/new-spillable-map {:a 1}),
   "spill-set" (spill/new-spillable-set #{1 2})})

(defn stress-fixtures
  "Every upstream leaf and the complete map, without type exclusions."
  []
  (let [data (nippy/stress-data {:comparable? false})]
    (into {"stress/complete" data}
          (concat
           (for [[k v] (dissoc data :non-comparable)] [(str "stress/" (name k)) v])
           (for [[k v] (dissoc (:non-comparable data) :arrays)] [(str "stress/non-comparable/" (name k)) v])
           (for [[k v] (get-in data [:non-comparable :arrays])] [(str "stress/arrays/" (name k)) v])))))

(defn fixtures [] (merge (native-fixtures) (stress-fixtures)))

(defn write-vectors!
  "Regenerate the checked-in corpus using the JVM's resolved Nippy version."
  [path]
  (let [rows (for [[id value] (sort-by key (fixtures))]
               (str id "\t" (bytes->hex (nippy/fast-freeze value))))]
    (spit path (str "# JVM Nippy fast-freeze; generated by nippy-support/write-vectors!\n"
                    (str/join "\n" rows) "\n"))))

(defn value=
  "Checks upstream values, including arrays and exceptions that lack value equality."
  [left right]
  (cond
    (and (instance? Throwable left) (instance? Throwable right))
    (and (= (class left) (class right))
         (= (.getMessage ^Throwable left) (.getMessage ^Throwable right))
         (value= (ex-data left) (ex-data right))
         (value= (.getCause ^Throwable left) (.getCause ^Throwable right))
         (java.util.Arrays/equals (.getStackTrace ^Throwable left)
                                  (.getStackTrace ^Throwable right)))

    (and (some? left) (some? right)
         (.isArray ^Class (class left)) (.isArray ^Class (class right)))
    (java.util.Objects/deepEquals left right)

    (and (map? left) (map? right))
    (and (= (set (keys left)) (set (keys right)))
         (= (meta left) (meta right))
         (every? (fn [[k v]] (value= v (get right k))) left))

    (and (sequential? left) (sequential? right))
    (and (= (count left) (count right)) (every? true? (map value= left right)))

    (and (instance? java.util.regex.Pattern left) (instance? java.util.regex.Pattern right))
    (and (= (.pattern ^java.util.regex.Pattern left) (.pattern ^java.util.regex.Pattern right))
         (= (.flags ^java.util.regex.Pattern left) (.flags ^java.util.regex.Pattern right)))

    :else (= left right)))
