#!/usr/bin/env python3
"""Generate the CIDR paper's data-backed SVG figures using only the stdlib."""

from __future__ import annotations

import csv
import html
import math
from pathlib import Path


HERE = Path(__file__).resolve()
PAPER_DIR = HERE.parent.parent
REPO_ROOT = HERE.parents[4]
FIGURE_DIR = PAPER_DIR / "figures"
RESULTS = REPO_ROOT / "benchmarks" / "JOB-bench" / "results"

SAMPLED_SLOWDOWNS = (
    RESULTS
    / "cidr-confirmatory-sampled-policies-20261001"
    / "optimizer_slowdowns_1785324090644.csv"
)
NO_SAMPLING_SLOWDOWNS = (
    RESULTS
    / "cidr-confirmatory-no-sampling-schedules-20261101"
    / "optimizer_slowdowns_1785332556151.csv"
)

FONT = "Helvetica,Arial,sans-serif"
INK = "#17212b"
MUTED = "#52606d"
GRID = "#d8dee4"
FULL = "#1f4e79"
SHRINK = "#008c95"
RAW = "#d55e00"
NO_COUNTS = "#7a5195"
NO_SAMPLING = "#9a6700"


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def attrs(**values: object) -> str:
    parts = []
    for key, value in values.items():
        if value is None:
            continue
        key = key.rstrip("_").replace("_", "-")
        parts.append(f'{key}="{esc(value)}"')
    return " ".join(parts)


def element(tag: str, body: str = "", **values: object) -> str:
    return f"<{tag} {attrs(**values)}>{body}</{tag}>"


def line(x1: float, y1: float, x2: float, y2: float, **values: object) -> str:
    return f"<line {attrs(x1=x1, y1=y1, x2=x2, y2=y2, **values)}/>"


def rect(x: float, y: float, width: float, height: float, **values: object) -> str:
    return f"<rect {attrs(x=x, y=y, width=width, height=height, **values)}/>"


def circle(cx: float, cy: float, radius: float, **values: object) -> str:
    return f"<circle {attrs(cx=cx, cy=cy, r=radius, **values)}/>"


def text(
    x: float,
    y: float,
    value: object,
    *,
    size: float = 12,
    weight: int | str = 400,
    anchor: str = "start",
    fill: str = INK,
    **values: object,
) -> str:
    return element(
        "text",
        esc(value),
        x=x,
        y=y,
        font_family=FONT,
        font_size=size,
        font_weight=weight,
        text_anchor=anchor,
        fill=fill,
        **values,
    )


def svg_document(
    width: int,
    height: int,
    title_value: str,
    description: str,
    body: str,
    *,
    definitions: str = "",
) -> str:
    return "\n".join(
        [
            '<?xml version="1.0" encoding="UTF-8"?>',
            (
                f'<svg xmlns="http://www.w3.org/2000/svg" '
                f'width="{width}" height="{height}" '
                f'viewBox="0 0 {width} {height}" role="img" '
                f'aria-labelledby="title desc">'
            ),
            element("title", esc(title_value), id="title"),
            element("desc", esc(description), id="desc"),
            element(
                "metadata",
                esc("Generated by scripts/generate_figures.py for the CIDR paper."),
            ),
            f"<defs>{definitions}</defs>" if definitions else "",
            rect(0, 0, width, height, fill="#ffffff"),
            body,
            "</svg>",
            "",
        ]
    )


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_svg(name: str, document: str) -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    (FIGURE_DIR / name).write_text(document, encoding="utf-8")


def query_graph_figure() -> None:
    width, height = 1000, 195
    definitions = """
      <marker id="query-arrow" markerWidth="9" markerHeight="7"
              refX="8" refY="3.5" orient="auto"
              markerUnits="strokeWidth">
        <path d="M0,0 L9,3.5 L0,7 Z" fill="#52606d"/>
      </marker>
    """
    parts: list[str] = []

    # Panel divisions and titles.
    parts.extend(
        [
            line(365, 7, 365, 189, stroke=GRID, stroke_width=1.3),
            line(765, 7, 765, 189, stroke=GRID, stroke_width=1.3),
            text(183, 17, "(a) Datalog query", size=14, weight=700, anchor="middle"),
            text(565, 17, "(b) Entity stars and attributes", size=14, weight=700, anchor="middle"),
            text(882, 17, "(c) Simplified query graph", size=14, weight=700, anchor="middle"),
        ]
    )

    # Panel (a): preserve conventional Datomic query formatting.
    query_lines = [
        "[:find ?title",
        " :where",
        " [?t :title/title ?title]",
        " [?t :title/production-year ?year]",
        " [(<= 2005 ?year 2010)]",
        " [?mc :movie-companies/movie ?t]",
        " [?mc :movie-companies/company ?c]",
        ' [?c :company-name/country-code "[us]"]]',
    ]
    for index, query_line in enumerate(query_lines):
        parts.append(
            element(
                "text",
                esc(query_line),
                x=18,
                y=39 + 20 * index,
                font_family="Consolas,Menlo,monospace",
                font_size=12.5,
                fill=INK,
                **{"xml:space": "preserve"},
            )
        )

    star_styles = {
        "?t": ("#e7f0f8", FULL),
        "?mc": ("#e5f5f3", SHRINK),
        "?c": ("#fff1e8", RAW),
    }

    def star_node(entity: str, x: float, y: float) -> None:
        fill, stroke = star_styles[entity]
        parts.append(
            rect(
                x,
                y,
                62,
                34,
                rx=17,
                fill=fill,
                stroke=stroke,
                stroke_width=2,
            )
        )
        parts.append(text(x + 31, y + 22, entity, size=14, weight=700, anchor="middle"))

    def attribute_box(
        x: float,
        y: float,
        width_value: float,
        label: str,
        *,
        size: float = 11.5,
    ) -> None:
        parts.append(
            rect(
                x,
                y,
                width_value,
                29,
                rx=5,
                fill="#f8fafc",
                stroke=GRID,
                stroke_width=1.2,
            )
        )
        parts.append(text(x + 8, y + 19, label, size=size))

    # Panel (b): each entity variable is the center of one star.
    star_node("?t", 383, 38)
    attribute_box(470, 28, 174, ":title/title → ?title")
    attribute_box(
        470,
        61,
        275,
        ":title/production-year → ?year; 2005 ≤ ?year ≤ 2010",
        size=10.8,
    )
    parts.extend(
        [
            line(445, 55, 470, 42, stroke=MUTED, stroke_width=1.5),
            line(445, 55, 470, 75, stroke=MUTED, stroke_width=1.5),
        ]
    )

    star_node("?mc", 383, 96)
    attribute_box(470, 88, 229, ":movie-companies/movie → ?t", size=11.2)
    attribute_box(470, 121, 250, ":movie-companies/company → ?c", size=11.2)
    parts.extend(
        [
            line(445, 113, 470, 102, stroke=MUTED, stroke_width=1.5),
            line(445, 113, 470, 135, stroke=MUTED, stroke_width=1.5),
        ]
    )

    star_node("?c", 383, 154)
    attribute_box(470, 157, 261, ':company-name/country-code → "[us]"', size=11.2)
    parts.append(line(445, 171, 470, 171, stroke=MUTED, stroke_width=1.5))

    # Panel (c): star collapse leaves only entity nodes and reference edges.
    graph_nodes = [
        (780, 75, 78, 46, "?mc", "movie company", "#e5f5f3", SHRINK),
        (910, 35, 75, 46, "?t", "title", "#e7f0f8", FULL),
        (910, 126, 75, 46, "?c", "company", "#fff1e8", RAW),
    ]
    for x, y, node_width, node_height, entity, role, fill, stroke in graph_nodes:
        parts.append(
            rect(
                x,
                y,
                node_width,
                node_height,
                rx=8,
                fill=fill,
                stroke=stroke,
                stroke_width=2,
            )
        )
        parts.append(text(x + node_width / 2, y + 20, entity, size=14, weight=700, anchor="middle"))
        parts.append(text(x + node_width / 2, y + 36, role, size=9.8, anchor="middle", fill=MUTED))

    parts.extend(
        [
            line(
                858,
                88,
                909,
                69,
                stroke=MUTED,
                stroke_width=2,
                marker_end="url(#query-arrow)",
            ),
            text(884, 61, ":movie", size=10.5, anchor="middle", fill=MUTED),
            line(
                858,
                108,
                909,
                140,
                stroke=MUTED,
                stroke_width=2,
                marker_end="url(#query-arrow)",
            ),
            text(884, 154, ":company", size=10.5, anchor="middle", fill=MUTED),
        ]
    )

    document = svg_document(
        width,
        height,
        "Running Datalog query and its entity-star graph",
        (
            "Three panels show a Datomic-flavored Datalog query, its triple "
            "patterns grouped into three entity stars with attributes and a "
            "year constraint, and the simplified three-node query graph. "
            "Stored references point from the movie-company star to the title "
            "and company stars, while indexes permit traversal in reverse."
        ),
        "\n".join(parts),
        definitions=definitions,
    )
    write_svg("query-graph.svg", document)


def architecture_figure() -> None:
    width, height = 1000, 170
    definitions = """
      <marker id="arrow" markerWidth="9" markerHeight="7" refX="8" refY="3.5"
              orient="auto" markerUnits="strokeWidth">
        <path d="M0,0 L9,3.5 L0,7 Z" fill="#52606d"/>
      </marker>
    """
    boxes = [
        (
            25,
            "EAV/AVE index counts",
            "maintained point & range counts",
            "remove avoidable uncertainty",
            "#e7f0f8",
            FULL,
        ),
        (
            275,
            "Query-local samples",
            "correlation & directional fanout",
            "expose query-specific uncertainty",
            "#e5f5f3",
            SHRINK,
        ),
        (
            525,
            "Storage-derived prior",
            "shrinkage or envelope",
            "manage sampling uncertainty",
            "#fff1e8",
            RAW,
        ),
        (
            775,
            "Physical plan",
            "merge scans, AVE scans & joins",
            "avoid catastrophic decisions",
            "#eeeaf5",
            NO_COUNTS,
        ),
    ]
    parts: list[str] = []
    for index, (x, heading, detail, role, fill, stroke) in enumerate(boxes):
        parts.append(
            rect(
                x,
                32,
                200,
                82,
                rx=8,
                fill=fill,
                stroke=stroke,
                stroke_width=2,
            )
        )
        parts.append(text(x + 100, 59, heading, size=15, weight=700, anchor="middle"))
        parts.append(text(x + 100, 82, detail, size=14, anchor="middle"))
        parts.append(text(x + 100, 137, role, size=13.5, anchor="middle", fill=MUTED))
        if index < len(boxes) - 1:
            parts.append(
                line(
                    x + 202,
                    73,
                    x + 243,
                    73,
                    stroke=MUTED,
                    stroke_width=2,
                    marker_end="url(#arrow)",
                )
            )
    parts.append(
        text(
            500,
            18,
            "Managing cardinality uncertainty",
            size=13.5,
            weight=700,
            anchor="middle",
        )
    )
    document = svg_document(
        width,
        height,
        "Managing cardinality uncertainty",
        (
            "A four-stage pipeline from EAV and AVE index counts through query-local "
            "samples and a storage-derived prior to physical plan selection."
        ),
        "\n".join(parts),
        definitions=definitions,
    )
    write_svg("architecture.svg", document)


def slowdown_series() -> tuple[dict[str, list[float]], dict[str, int]]:
    sampled = read_csv(SAMPLED_SLOWDOWNS)
    schedules = read_csv(NO_SAMPLING_SLOWDOWNS)
    condition_map = {
        "production-floor": "Full",
        "shrink": "Shrinkage",
        "raw": "Raw",
        "no-counts": "No counts",
    }
    series: dict[str, list[float]] = {name: [] for name in condition_map.values()}
    timeouts: dict[str, int] = {name: 0 for name in condition_map.values()}
    for row in sampled:
        condition = row["Condition"]
        if condition not in condition_map:
            continue
        name = condition_map[condition]
        series[name].append(float(row["Slowdown"]))
        if row["Status"] == "timeout":
            timeouts[name] += 1
    series["No sampling"] = []
    timeouts["No sampling"] = 0
    no_sampling_catastrophes = 0
    for row in schedules:
        if row["Condition"] != "no-sampling":
            continue
        slowdown = float(row["Slowdown"])
        series["No sampling"].append(slowdown)
        if row["Status"] == "timeout":
            timeouts["No sampling"] += 1
        if row["Status"] == "timeout" or slowdown >= 10.0:
            no_sampling_catastrophes += 1

    for name in ("Full", "Shrinkage", "Raw", "No counts"):
        assert len(series[name]) == 3390, (name, len(series[name]))
    assert len(series["No sampling"]) == 1130
    assert timeouts["Full"] == 0
    assert timeouts["Shrinkage"] == 0
    assert timeouts["Raw"] == 0
    assert timeouts["No counts"] == 30
    assert timeouts["No sampling"] == 80
    assert no_sampling_catastrophes == 256
    return series, timeouts


def tail_figure() -> None:
    series, timeouts = slowdown_series()
    width, height = 520, 350
    left, top, plot_width, plot_height = 58, 78, 445, 220
    xmin, xmax = 1.0, 1000.0
    ymin, ymax = 1.0e-4, 1.0

    def sx(value: float) -> float:
        return left + math.log10(value / xmin) / math.log10(xmax / xmin) * plot_width

    def sy(value: float) -> float:
        return top + math.log10(ymax / value) / math.log10(ymax / ymin) * plot_height

    definitions = (
        f'<clipPath id="tail-clip">{rect(left, top, plot_width, plot_height)}</clipPath>'
    )
    parts: list[str] = []
    parts.append(text(width / 2, 17, "Execution-time tail", size=16, weight=700, anchor="middle"))

    x_ticks = [1, 10, 100, 1000]
    for tick in x_ticks:
        x = sx(tick)
        parts.append(line(x, top, x, top + plot_height, stroke=GRID, stroke_width=0.8))
        parts.append(text(x, top + plot_height + 17, str(tick), size=14, anchor="middle"))
    y_ticks = [(1.0, "1"), (0.1, "10⁻¹"), (0.01, "10⁻²"), (0.001, "10⁻³"), (0.0001, "10⁻⁴")]
    for tick, label in y_ticks:
        y = sy(tick)
        parts.append(line(left, y, left + plot_width, y, stroke=GRID, stroke_width=0.8))
        parts.append(text(left - 8, y + 4, label, size=13.5, anchor="end"))
    parts.append(
        line(left, top + plot_height, left + plot_width, top + plot_height, stroke=INK, stroke_width=1.2)
    )
    parts.append(line(left, top, left, top + plot_height, stroke=INK, stroke_width=1.2))
    parts.append(
        text(
            left + plot_width / 2,
            height - 13,
            "slowdown",
            size=15,
            anchor="middle",
        )
    )
    parts.append(
        text(
            15,
            top + plot_height / 2,
            "Pr[slowdown ≥ x]",
            size=15,
            anchor="middle",
            transform=f"rotate(-90 15 {top + plot_height / 2})",
        )
    )
    threshold_x = sx(10.0)
    parts.append(
        line(
            threshold_x,
            top,
            threshold_x,
            top + plot_height,
            stroke="#6b7280",
            stroke_width=1.1,
            stroke_dasharray="3 3",
        )
    )
    parts.append(
        text(
            threshold_x + 4,
            top + 12,
            "10× threshold",
            size=12.5,
            fill=MUTED,
        )
    )

    styles = {
        "Full": (FULL, ""),
        "Shrinkage": (SHRINK, ""),
        "Raw": (RAW, "6 3"),
        "No counts": (NO_COUNTS, "2 2"),
        "No sampling": (NO_SAMPLING, "8 3 2 3"),
    }
    thresholds = [10 ** (3 * index / 240) for index in range(241)]
    for name in ("No sampling", "No counts", "Raw", "Shrinkage", "Full"):
        values = sorted(series[name])
        points = []
        for threshold in thresholds:
            exceed = sum(value >= threshold for value in values)
            if exceed == 0:
                break
            probability = exceed / len(values)
            if probability < ymin:
                continue
            points.append(f"{sx(threshold):.2f},{sy(probability):.2f}")
        color, dash = styles[name]
        parts.append(
            f'<polyline points="{" ".join(points)}" fill="none" '
            f'stroke="{color}" stroke-width="2.1" '
            f'stroke-linejoin="round" stroke-linecap="round" '
            f'stroke-dasharray="{dash}" clip-path="url(#tail-clip)"/>'
        )

    legend_items = [
        ("Full · 30 seeds", "Full", 62, 36),
        ("Shrinkage · 30", "Shrinkage", 226, 36),
        ("Raw · 30", "Raw", 388, 36),
        ("No counts · 30 TO", "No counts", 130, 59),
        ("No sampling · 80 TO", "No sampling", 310, 59),
    ]
    for label, name, x, y in legend_items:
        color, dash = styles[name]
        parts.append(
            line(
                x,
                y - 3,
                x + 25,
                y - 3,
                stroke=color,
                stroke_width=2.4,
                stroke_dasharray=dash,
            )
        )
        parts.append(text(x + 31, y, label, size=14))

    document = svg_document(
        width,
        height,
        "Execution-time slowdown tail",
        (
            "Complementary cumulative distributions of slowdown for "
            "Full, Shrinkage, Raw, No counts, and No sampling. The no-counts "
            "and no-sampling curves include 30 and 80 timeouts respectively."
        ),
        "\n".join(parts),
        definitions=definitions,
    )
    write_svg("tail-ccdf.svg", document)


def main() -> None:
    query_graph_figure()
    architecture_figure()
    tail_figure()
    print(f"generated figures in {FIGURE_DIR}")


if __name__ == "__main__":
    main()
