(ns datalevin.wire-compression-test
  (:require [clojure.test :refer [deftest is use-fixtures]]
            [datalevin.bits :as b]
            [datalevin.client :as client]
            [datalevin.constants :as c]
            [datalevin.core :as d]
            [datalevin.native-value :as nv]
            [datalevin.protocol :as p]
            [datalevin.protocol.context :as context]
            [datalevin.server :as server]
            [datalevin.test.core :refer [allocate-port db-fixture]]
            [datalevin.util :as u]
            [taoensso.nippy :as nippy])
  (:import [com.github.luben.zstd Zstd]
           [datalevin.io WireCompression]
           [datalevin NativeValue]
           [java.io DataInput DataOutput]
           [java.nio ByteBuffer BufferOverflowException]
           [java.nio.channels SelectionKey]
           [java.util Random]
           [java.util.function BiPredicate]))

(use-fixtures :once db-fixture)
(def opts {:compression :zstd :compression-threshold 0 :compression-level 3})

(defn- frame ^ByteBuffer [value fmt direct? size]
  (doto (if direct? (ByteBuffer/allocateDirect size) (ByteBuffer/allocate size))
    (p/write-message-bf value fmt opts) (.flip)))

(defn- decode [^ByteBuffer bf]
  (let [fmt (.get bf)]
    (.getInt bf)
    (p/read-value fmt bf opts)))

(deftest negotiated-policy-and-legacy-peers
  (doseq [compression [:none :zstd]]
    (let [policy (p/client-wire-opts {:wire-compression compression
                                    :wire-compression-threshold 12345
                                    :wire-compression-level -1})
          server (p/negotiate-wire-opts (p/local-wire-capabilities policy))
          client (p/negotiate-wire-opts (p/local-wire-capabilities server) policy)]
      (is (= policy (select-keys server (keys policy)) (select-keys client (keys policy))))))
  (is (nil? (:compression (p/negotiate-wire-opts nil))))
  (is (= :zstd (:compression (p/negotiate-wire-opts {:compression [:zstd]}))))
  (is (= c/*wire-compression-threshold*
         (:compression-threshold (p/negotiate-wire-opts
                                   {:compression [:zstd] :compression-threshold 1}))))
  (doseq [invalid [{:wire-compression true} {:wire-compression nil}
                   {:wire-compression-threshold -1} {:wire-compression-threshold 2.5}
                   {:wire-compression-level 100}]]
    (is (thrown? Exception (p/client-wire-opts invalid)))))

(deftest direct-and-heap-frames-keep-wire-compatibility
  (with-open [ctx (context/create)]
    (context/with-context ctx
      (doseq [fmt [c/message-format-nippy c/message-format-transit]
              direct? [false true]
              size [256 65536]]
        (let [value {:data (.repeat "large" 1000)}
              ^ByteBuffer encoded (frame value fmt direct? size)
              flag (.get encoded)
              _ (.getInt encoded)
              raw-size (.getInt encoded)
              compressed (b/get-bytes encoded)
              raw (Zstd/decompress compressed raw-size)]
          (is (pos? (bit-and flag c/message-flag-zstd)))
          (is (= value (p/read-value fmt raw)))
          (is (= value (decode (frame value fmt direct? size))))))
      ;; Frames generated by the old byte-array compressor remain readable.
      (let [value {:legacy (.repeat "old" 3000)}
            raw (doto (ByteBuffer/allocate 20000) (p/write-nippy-bf value) (.flip))
            bytes (b/get-bytes raw)
            packed (Zstd/compress bytes 3)
            body (doto (ByteBuffer/allocate (+ 4 (alength packed)))
                   (.putInt (alength bytes)) (.put packed) (.flip))]
        (is (= value (p/read-value (bit-or c/message-format-nippy c/message-flag-zstd)
                                  body opts))))
      ;; Incompressible frames and nonzero offsets do not corrupt the following frame.
      (let [bytes (byte-array 10000)
            _ (.nextBytes (Random. 42) bytes)
            bf (ByteBuffer/allocateDirect 50000)]
        (.position bf 17)
        (p/write-message-bf bf bytes c/message-format-nippy opts)
        (let [end (.position bf)]
          (p/write-message-bf bf {:next :frame} c/message-format-nippy opts)
          (.flip bf)
          (.position bf 17)
          (let [first-frame (doto (.duplicate bf) (.limit end))]
            (is (java.util.Arrays/equals bytes ^bytes (decode first-frame))))
          (.position bf end)
          (is (= {:next :frame} (decode bf))))))))

(defrecord NestedCompressed [value])
(nippy/extend-freeze NestedCompressed ::nested-compressed
  [v ^DataOutput out]
  (let [bytes (b/get-bytes (frame (:value v) c/message-format-nippy true 256))]
    (.writeInt out (alength bytes)) (.write out bytes)))
(nippy/extend-thaw ::nested-compressed
  [^DataInput in]
  (let [bytes (byte-array (.readInt in))]
    (.readFully in bytes)
    (->NestedCompressed (decode (ByteBuffer/wrap bytes)))))

(deftest buffer-leases-survive-recursive-codecs-failures-and-deferred-requests
  (with-open [ctx (context/create)]
    (context/with-context ctx
      (let [text (.repeat "repeat" 2000)
            value [(->NestedCompressed {:inner text}) {:outer text}]
            native (NativeValue. "sender" ":app/value" (b/serialize 7)
                                 (reify BiPredicate (test [_ a b] (identical? a b))))]
        (is (= value (decode (frame value c/message-format-nippy true 256))))
        (is (thrown? BufferOverflowException (frame value c/message-format-nippy true 6)))
        (doseq [prefix [-1 1 20000000]]
          (let [bad (frame {:data text} c/message-format-nippy true 256)]
            (.putInt bad 5 prefix)
            (is (thrown? Exception (decode bad)))))
        (let [bf (frame {:type :request :value native :padding text}
                        c/message-format-nippy true 512)
              fmt (.get bf)
              _ (.getInt bf)
              parsed (p/read-request fmt bf opts)]
          (is (p/native-request? parsed))
          (is (= value (decode (frame value c/message-format-nippy true 256))))
          (binding [nv/*wire-reader* (fn [type bytes] [type (b/deserialize bytes)])]
            (is (= [":app/value" 7] (:value (p/resolve-native-request parsed)))))))
      (context/with-compression [a]
        (context/with-compression [b]
          (is (not (identical? a b)))))
      (let [a (context/acquire-compression! ctx)]
        (context/release-compression! ctx a)
        (let [b (context/acquire-compression! ctx)]
          (is (identical? a b))
          (context/release-compression! ctx b)))))
  (let [codec (WireCompression.)]
    (.close codec)
    (.close codec)
    (is (thrown? IllegalStateException (.encodingBuffer codec 10)))))

(deftest threshold-is-the-uncompressed-payload-size
  (let [value (.repeat "threshold" 100)
        raw (doto (ByteBuffer/allocate 10000) (p/write-nippy-bf value))
        size (.position raw)]
    (doseq [[threshold compressed?] [[size true] [(inc size) false]]]
      (let [bf (ByteBuffer/allocateDirect 10000)]
        (p/write-message-bf bf value c/message-format-nippy
                            (assoc opts :compression-threshold threshold))
        (is (= compressed? (pos? (bit-and (.get bf 0) c/message-flag-zstd))))))))

(deftest connection-policy-survives-replacement-and-derived-clients
  (let [root (u/tmp-dir (str "wire-compression-" (random-uuid)))
        port (allocate-port)
        srv (server/create {:root root :port port})
        uri (str "dtlv://datalevin:datalevin@localhost:" port "/wire")
        seen (atom [])
        handlers @#'server/message-handler-map
        tracked (into {} (map (fn [[type handler]]
                               [type (fn [srv key message]
                                       (when (#{:get-value :transact-kv} type)
                                         (swap! seen conj (:wire-opts @(.attachment ^SelectionKey key))))
                                       (handler srv key message))])) handlers)]
    (try
      (server/start srv)
      (with-redefs-fn {#'server/message-handler-map tracked}
        #(doseq [mode [:none :zstd]]
           (let [policy {:wire-compression mode :wire-compression-threshold 4321
                         :wire-compression-level 1}
                 kv (d/open-kv uri {:client-opts (assoc policy :pool-size 2)})
                 base (.-client ^datalevin.remote.KVStore kv)
                 value (.repeat "data" 5000)]
             (try
               (reset! seen [])
               (d/open-dbi kv "data")
               (d/transact-kv kv [[:put "data" 1 value :id :data]])
               (is (= value (d/get-value kv "data" 1 :id :data)))
               (let [pool (client/get-pool base)
                     conn (client/get-connection pool)]
                 (client/close conn)
                 (client/release-connection pool conn))
               (is (= value (d/get-value kv "data" 1 :id :data)))
               (let [id (client/get-id base)]
                 (#'server/remove-client srv id)
                 (is (= value (d/get-value kv "data" 1 :id :data)))
                 (is (not= id (client/get-id base)))
                 (is (= policy (client/wire-client-options base))))
               (d/with-transaction-kv [tx kv]
                 (is (= value (d/get-value tx "data" 1 :id :data))))
               (let [retry (#'client/new-client-for-endpoint
                             (#'client/client-routing-context base) "localhost" port)]
                 (try (is (= policy (client/wire-client-options retry)))
                      (finally (client/close-client retry))))
               (is (<= 4 (count @seen)))
               (is (every? (fn [actual]
                             (= (p/client-wire-opts policy)
                                (select-keys actual (keys (p/client-wire-opts policy))))) @seen))
               (finally (d/close-kv kv))))))
      (finally (server/stop srv) (u/delete-files root)))))
